#!/bin/bash
# Шел скрипт подкаст плейър за http://www.nerds2nerds.com/

# Автор: Ivaylo Kuzev

# This script is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# This script is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, see <https://www.gnu.org/licenses/gpl-3.0.txt>

clear;

# Името на програмата
PROG="${0##*/}"

# Цветен текст
red=$'\e[0;31m'
green=$'\e[0;32m'
ylw=$'\e[0;33m'
blue=$'\e[0;34m'
pur=$'\e[0;35m'
cyn=$'\e[1;36m'
end=$'\e[0m'

# Провери за зависимостите
if ! which mplayer &>/dev/null; then
  printf "%s\n" "${red}Изисква да имате инсталиран пакета mplayer${end}"
  exit 1
fi

if ! which wget &>/dev/null; then
  printf "%s\n" "${red}Изисква да имате инсталиран пакета wget${end}"
  exit 1
fi

# Уеб страницата
RSS_URI="http://www.nerds2nerds.com/podcasts/"
# Файл, съдържащ линковете към всички подкасти
PLAYLIST="${HOME}/.nerds2nerds_podcast.m3u"
# Плейър
PLAY_COMMAND="mplayer -quiet -nolirc -prefer-ipv4 -playlist"

# Помощтен текст
usage() {
  cat <<EOF
usage: $PROG [опция]

Шел скрипт подкаст плейър за http://www.nerds2nerds.com/

Опции:
   -h, --help        Показва този помощен текст.
   -u, --update      Създай/Обнови списъка със подкасти.
   -p, --play        Пуска последният подкаст.

Примери:
   $PROG -u  -- за да създадете списъка със наличните подкасти
   $PROG -p  -- за да стартирате последният най нов епизод от списъка

EOF
exit 0
}

# Обнови листата
update(){
  printf "%s\n" "${ylw}Обновяване на подкаст епизодите. Моля изчакайте...${end}"
  wget -r --spider -nd -l1 -A ogg $RSS_URI 2>&1 | grep -Eio http.+ogg | sort -r | uniq  > "$PLAYLIST" &
  pid=$!
  spin='-\|/'
  delay=0.15
  i=0
  while kill -0 $pid 2>/dev/null; do
    i=$(( (i+1) %4 ))
    printf "\r[${spin:$i:1}]";
    sleep "$delay";
  done
  printf "%s\n" "${green}Подкаст епизодите бяха обновени!${end}"
}

# Стартира плейъра
play(){
  if [ ! -f "${HOME}/.nerds2nerds_podcast.m3u" ]; then
    update;
    sleep 3;
    clear;
  fi
  printf "%s\n" "${blue}                        __    __                        __    "
  printf "%s\n" "   ____  ___  _________/ /___|__ \ ____  ___  _________/ /____"
  printf "%s\n" "  / __ \/ _ \/ ___/ __  / ___/_/ // __ \/ _ \/ ___/ __  / ___/"
  printf "%s\n" " / / / /  __/ /  / /_/ (__  ) __// / / /  __/ /  / /_/ (_   ) "
  printf "%s\n" "/_/ /_/\___/_/   \__,_/____/____/_/ /_/\___/_/   \__,_/____/  ${end}"
  printf "%s\n" "----------------------------->>> ${cyn}http://www.nerds2nerds.com${end}"
  printf "%s\n" "${pur}Натиснете ${ylw}'q'${end}${pur} за да излезете${end}"
  printf "%s\n" "${pur}Регулирайте силата на звука със vol- ${ylw}'9'${end}${pur} и vol+ ${end}${ylw}'0'${end}"
  printf "%s\n" "${pur}За да паузирате ${end}${ylw}'p'${end}${pur} за изключване на звука ${end}${ylw}'m'${end}"
  printf "%s\n" "${pur}Използвайте ${end}${ylw}'<'${end} ${pur}и${end} ${ylw}'>'${end}${pur} за смяна на подкаст епизодите${end}"
  printf "%s\n" "${pur}Използвайте ${end}${ylw}'UP'${end} ${pur}и${end} ${ylw}'DOWN'${end}${pur} за превъртане 1 минута, напред и назад в епизода${end}"
  printf "%s\n" "${pur}Използвайте ${end}${ylw}'PGUP'${end} ${pur}и${end} ${ylw}'PGDWN'${end}${pur} за превъртане 10 минути, напред и назад в епизода${end}"
  $PLAY_COMMAND "$PLAYLIST" 2>&1 | GREP_COLOR='0;32' egrep --color=always -i "Playing"
}

# Получи опциите
case "$1" in
  -h|--help)
    usage
    ;;
  -u|--update)
    update
    ;;
  -p| --play)
    play
    ;;
  -* | --*)
    printf "%s\n" "${red}Няма такава опция $1${end}"
    ;;
  *)
    usage
    ;;
esac


exit 0
